### ISSUE TITLE
Pretrained model AutoDownload error

### ISSUE THREAD

**Issue by Amnx404** [bcmi/libcom#21]
Multiple automatic downloads are often done with broken symlinks, forcing me to manually fix them for all the tests. Secondly, shared pre-trained models like Vit are often broken again and again when the Zip file function is envoked.

**Comment by bo-zhang-cs** [comment]
Thanks for your report. It appears that the problem arose due to your internet connection. You can manually download the pretrained model by following the instructions [here](https://github.com/bcmi/libcom/blob/main/docs/get_started.md#download-pretrained-models). Please note that the correct directory to store pretrained models can be identified from the printed message during the automatic download process.

**Comment by Amnx404** [comment]
Ah, no I checked it again and again on multiple devices. Broken symlinks were a consistent issue throughout. I have also tried the same on paperspace servers in the cloud.
![CleanShot 2024-01-24 at 07 26 02@2x](https://github.com/bcmi/libcom/assets/91665648/5efa0c9d-f4fb-407c-a065-90558cfbdffa)
The symlink was broke, I didnt need to download it again, I simply corrected the symlink from terminal and it started to work. Also the shared pretrained model Vit, was not working even when I downloaded it manually, I simply removed the hugging face manual download part of the code. Unzipped and only then it started working. I have tried it on three systems, linux and windows and also on cloud, none seem to solve this issue.

**Comment by bo-zhang-cs** [comment]
Hi, after rechecking, I've identified the bug, which stems from the failure of `shutil.move` to relocate the target file of a symlink. I have addressed this issue in the [following commit](https://github.com/bcmi/libcom/blob/b6bd5c79d6fa9a4906c5ab4115305d2ff686cab6/libcom/utils/model_download.py#L38). Please download the latest code and give it another try.
